import React from "react";

const EnvironmentalPolicy = () => {
    return (
        <div className="textAlani">
            <h1 className="ustbaslik">ENVIRONMENTAL POLICY</h1>
            <h2 className="altbaslik">
                At KEKO Office Products, we are dedicated to conducting our business in an environmentally responsible manner. We recognize the urgent need to protect our planet, and our Environmental Policy reflects our commitment to sustainability and reducing our environmental footprint.

                <strong>Our Commitments:</strong>
                <ul>
                    <li>Sustainable Products: Offer a wide range of eco-friendly office products made from recycled or sustainable materials and work with suppliers who share our commitment to environmental responsibility.</li>
                    <li>Energy Efficiency: Minimize energy consumption across our operations by using energy-efficient technologies and transitioning towards renewable energy sources wherever feasible.</li>
                    <li>Waste Reduction: Implement waste management programs to reduce, reuse, and recycle materials, and encourage the use of digital processes to reduce paper consumption.</li>
                    <li>Carbon Footprint Reduction: Optimize logistics and supply chains to reduce greenhouse gas emissions and support initiatives aimed at offsetting carbon emissions generated by our operations.</li>
                    <li>Water Conservation: Promote water-saving practices within our facilities and operations and work with suppliers to encourage water-efficient production processes.</li>
                    <li>Awareness and Engagement: Educate employees, customers, and stakeholders about the importance of environmental conservation and encourage environmentally conscious behavior throughout our organization.</li>
                </ul>

                <strong>Our Approach:</strong> KEKO is committed to continuous improvement and innovation in environmental practices. We regularly review and update our policies to ensure they align with the latest sustainability standards and industry best practices. By embedding environmental stewardship into every aspect of our business, KEKO aims to lead by example, contributing to a greener, more sustainable future for Bulgaria, the European Union, and beyond. Together, we can create a positive impact on our planet.
            </h2>
        </div>
    );
};
export default EnvironmentalPolicy;